config/routes.rb
Rails.application.routes.draw do
  resources :bookshelves do
    collection do
      get "bookshelf_records", to: "bookshelves#bookshelf_records"
    end
  end
  resources :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :name, :author_name, :rating, presence: true
  validates :bookshelves_count, presence: { message: "Choose at least 1 bookshelf" }
  validates :rating, numericality: { message: "Rating should be a number" }
  validates_uniqueness_of :name, case_sensitive: true, message: "Book Name already exist"
end

app/models/bookshelf.rb
class Bookshelf < ActiveRecord::Base
  serialize :book_ids, Array
  validates :title, presence: { message: "Bookshelf Title must not be empty" }
  validates :description, presence: { message: "Please add description for the bookshelf" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @books = Book.new(books_params)
    bookshelves = params["book"]["bookshelves_id"]
    @books.bookshelves_count = bookshelves.present? ? bookshelves.count : nil
    if @books.save
      shelves
      flash[:notice] = "Book Created Successfully"
      redirect_to bookshelves_path
    else
      render :new
    end
  end

  def destroy
    begin
      bookshelf = Bookshelf.find_by_id(params["bookshelf"])
      book = Book.find_by_id(params["id"])
      book.bookshelves_count -= 1
      bookshelf.book_ids.delete(book.id)
      book.bookshelves_count.zero? ? book.delete : book.save
      bookshelf.save
    rescue
      flash[:error] = "Something went wrong please try again"
    else
      flash[:notice] = "Successfully deleted book from bookshelf"
    end
    redirect_to :back
  end

  def edit
    book = Book.find_by_id(params["id"])
    if book.update_attributes(books_params)
      flash[:notice] = "Update Successful"
    else
      flash[:error] = "Something went wrong please try again"
    end
    redirect_to :back
  end

  private

  def shelves
    params["book"]["bookshelves_id"].keys.each do |bs_id|
      shelf = Bookshelf.find(bs_id)
      shelf.book_ids << @books.id
      shelf.save
    end
  end

  def books_params
    params.require(:book).permit(:name, :author_name, :rating, :bookshelves_count)
  end
end

app/controllers/bookshelves_controller.rb
class BookshelvesController < ApplicationController
  def index
    @bookshelf_record = []
    if params[:search].present?
      @bookshelf_record = Bookshelf.find_by_id(extract_data)
    end
  end

  def create
    bookshelf = Bookshelf.new(bookshelf_params)
    if bookshelf.save
      flash["notice"] = "Bookshelf Created Successfully"
    end
    redirect_to bookshelves_path
  end

  def edit
    bookshelf = Bookshelf.find_by_id(params["id"])
    if bookshelf.update_attributes(bookshelf_params)
      flash[:notice] = "Update Successful"
    else
      flash[:error] = "Something went wrong please try again"
    end
    redirect_to :back
  end

  def destroy
    begin
      bookshelf = Bookshelf.find_by_id(params["id"])
      shelf_book_count(bookshelf.book_ids)
      bookshelf.delete
    rescue
      flash[:error] = "Something went wrong please try again"
    else
      flash[:notice] = "Successfully deleted bookshelf"
    end
    redirect_to bookshelves_path
  end

  private

  def shelf_book_count(shelf_ids)
    shelf_ids.each do |b_id|
      book = Book.find(b_id)
      book.bookshelves_count -= 1
      book.bookshelves_count.zero? ? book.delete : book.save
    end
  end

  def extract_data
    params[:search][:sort_by].present? ? params[:search][:description_id] : params[:search].values.first
  end

  def bookshelf_params
    params.require(:bookshelf).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_param
    params[:search] || {}
  end
end

app/views/books/_book_edit_modal.html.slim
button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#bookEditModal#{book_record.id}"
  | Edit Book
div class="modal fade" id="bookEditModal#{book_record.id}" role="dialog"
  div class="modal-dialog"
    div class="modal-content"
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal"
          | X
        h4 class="modal-title"
          | Edit Book
        div class="modal-body"
          = simple_form_for(book_record, url: edit_book_path(book_record.id), method: :get) do |f|
            = f.input_field :name, placeHolder: "Input Book Name", class: "form-control", style: "resize:none"
            br
            = f.input_field :author_name, placeHolder: "Input Author Name", class: "form-control", style: "resize:none"
            br
            = f.input_field :rating, placeHolder: "Input Book Rating", class: "form-control", style: "resize:none"
            br
            = f.button :submit, class: "btn btn-primary"
        div class="modal-footer"

app/views/books/_edit_modal.html.slim
div class="modal fade" id="bookEditModal" role="dialog"
  div class="modal-dialog"
    div class="modal-content"
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal"
          | X
        h4 class="modal-title"
          | Edit Bookshelf
        div class="modal-body"
        div class="modal-footer"

app/views/books/new.html.slim
div class="bookshelf header"
  div class="constrain text-center"
    h1 Add Books

  - if @books.present? && @books.errors.any?
    div class="alert alert-danger"
      - @books.errors.messages.map do |key, message|
        = message.first

  div class="row"
    div class="col-md-2 col-md-offset-5"
      = simple_form_for(Book.new, url: books_path, :method => :post) do |f|
        = f.input_field :name, placeHolder: "Input Book Name", class: "form-control", style: "resize:none"
        br
        = f.input_field :author_name, placeHolder: "Input Author Name", class: "form-control", style: "resize:none"
        br
        = f.input_field :rating, placeHolder: "Input Book Rating", class: "form-control", style: "resize:none"
        br
        | Please Choose Bookshelves
        - Bookshelf.all.map do |shelf|
          span.checkbox-bookshelf
            input name="book[bookshelves_id][#{shelf.id}]" type="checkbox"
            | #{shelf.description}
            br
        br
        = f.button :submit, class: "btn btn-primary"

app/views/bookshelves/_edit_modal.html.slim
div class="modal fade" id="editModal" role="dialog"
  div class="modal-dialog"
    div class="modal-content"
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal"
          | X
        h4 class="modal-title"
          | Edit Bookshelf
        div class="modal-body"
          = simple_form_for(@bookshelf_record, url: edit_bookshelf_path(@bookshelf_record.id), method: :get) do |f|
            = f.input_field :title, placeHolder: "Input Bookshelf Title", class: "form-control", style: "resize:none"
            br
            = f.input_field :description, placeHolder: "Input Bookshelf Description", class: "form-control", style: "resize:none"
            br
            = f.button :submit, class: "btn btn-primary"
        div class="modal-footer"

app/views/bookshelves/_show_bookshelf_records.html.slim
div class="constrain text-center"
  h1 = @bookshelf_record.title
  h4 = @bookshelf_record.description
  button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#editModal"
    | Edit Bookshelf
  = link_to "Delete Bookshelf", bookshelf_path(@bookshelf_record.id), class: "btn btn-md btn-info", method: :delete, data: {confirm: "Are you sure you want to delete the Bookshelf?"}, style: "margin-left:15px"
  - if @bookshelf_record.book_ids.present?
    div class="col-md-1 col-md-offset-8"
      = simple_form_for(:search, url: bookshelves_path, method: :get) do |f|
        | Books Sort:
        = f.input_field :sort_by, collection: [["Ascending", "ASC"], ["Descending", "DESC"]] , selected: get_param["sort_by"], onchange: "this.form.submit()", class: "form-control"
        = f.hidden_field :description_id, value: @bookshelf_record.id
    div class="col-md-2 col-md-offset-5"
      - book_list = params[:search][:sort_by].eql?("DESC") ? @bookshelf_record.book_ids.reverse : @bookshelf_record.book_ids
      - book_list.each do |book_id|
        - book_record = Book.find(book_id)
        | Book Name: 
        = book_record.name
        br
        | Author Name: 
        = book_record.author_name
        br
        | Rating: 
        = book_record.rating
        br
        div class="row"
          = render partial: "books/book_edit_modal", :locals => { book_record: book_record }
          = link_to "Delete Book", book_path(book_record, bookshelf: @bookshelf_record), class: "btn btn-md btn-info", method: :delete, data: {confirm: "Are you sure you want to delete the Bookshelf?"}, style: "margin-left:15px"
        br
        br
        br
  - else
    br
    br
    h2
      | No books record for this shelf

= render partial: "edit_modal"

app/views/bookshelves/index.html.slim
div class="bookshelf header"
  div class="constrain text-center"
    h1 Bookshelves

  - if flash[:error].present?
    div class="alert alert-danger"
      = flash[:error]
  - elsif flash[:notice].present?
    div class="alert alert-success"
      = flash[:notice]

  div class="row"
    div class="col-md-2 col-md-offset-2"
      = simple_form_for(Bookshelf.new, url: bookshelves_path, :method => :post) do |f|
        = f.input_field :title, placeHolder: "Input Bookshelf Title", class: "form-control", style: "resize:none"
        br
        = f.input_field :description, placeHolder: "Input Bookshelf Description", class: "form-control", style: "resize:none"
        br
        = f.button :submit, class: "btn btn-primary"

    div class="col-md-2 col-md-offset-4"
      = link_to "Add Books", new_book_path, class: "btn btn-default"

  div class="row"
    div class="col-md-2 col-md-offset-5"
      = simple_form_for(:search, url: bookshelves_path, method: :get) do |f|
        = f.input_field :description_id, collection: Bookshelf.all.map{ |record| [record.title, record.id] }.unshift(["Bookshelf List", 0]), selected: get_param["description_id"], onchange: "this.form.submit()", class: "form-control"

- if @bookshelf_record.present?
  = render partial: "show_bookshelf_records"

- content_for :extra_javascripts do
  = javascript_include_tag "bookshelf"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshelf Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>
</html>